prec    = 32
gpu     = false
dir     = "."

[data]
val_data    = "./val"
test_data   = "./test"
train_data  = "./train"
val_batch   = "auto" # Auto treats entire test set as one batch
test_batch  = "auto" # Auto treats entire test set as one batch
train_batch = 250
[data.info]
nfeatures   = "auto" # Height of input data
nchannels   = "auto" # Number of input data channels
nlabels     = "auto" # Number of output labels
labmean     = "auto" # Label means
labwidth    = "auto" # Label distribution widths
labnames    = ["mwf", "sind(alpha)"] # Target labels
labweights  = [1.0, 1.0] # Weights for loss function
labscale    = [100.0, 1.0] # scale labels before plotting
labunits    = ["%", "sind(deg)"] # label units, after scaling
# labnames    = ["mwf", "iewf", "T2iew/TE", "T2mw/TE", "alpha", "log(TE*K)", "T1iew/TE", "T1mw/TE"] # Target labels
# labweights  = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # Weights for loss function
# labscale    = [100.0, 100.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # scale labels before plotting
# labunits    = ["%", "%", "ms/ms", "ms/ms", "deg", "log(s*um/s)", "ms/ms", "ms/ms"] # label units, after scaling
[data.filter]
labnames    = [ "K",  "nTE" ]
lower       = [ 0.00,  32.0 ]
upper       = [ 1.00,  48.0 ]
[data.preprocess]
shuffle     = true
SNR         = [50.0, 0.0] # Additive random noise
[data.preprocess.chunk]
apply       = true
size        = 32

[model]
loss      = "l2"
acc       = "rmse"
[model.DenseLIGOCVAE]
Zdim      = 15
act       = "leakyrelu"

[optimizer]
epochs  = 5000
savemod = 1
testmod = 1
[optimizer.ADAM]
lr      = 1e-3
beta    = [0.9, 0.999]
decay   = 1e-5
[optimizer.SGD]
lr      = 3e-4
rho     = 0.9
decay   = 1e-5
