[data]
out       = "./output/tmp"
# ntheta    = 5
# nsignal   = 128
# theta_labels = ["freq", "phase", "offset", "amp", "tconst"]
# ntheta    = 5
# nsignal   = 48
# theta_labels = ["refcon", "alpha", "T2short", "dT2", "Ashort"]
ntheta    = 4
nsignal   = 48
echotime  = 8e-3
theta_labels = ["alpha", "T2short", "dT2", "Ashort"]

[mmd]
stepsize   = 3.1623e-4 #1.0e-5 #TODO
stepdrop   = 3.1623 #10.0 3.1623 #1.7783
stepthresh = 0.9e-7
steprate   = 2500
batchsize  = 2048 #3072
nbatches   = 10
epochs     = 999_999
traintime  = 1e9 #18000.0 #TODO
saveperiod = 120.0 #300.0 #TODO
showrate   = 1 #TODO
lambda     = 0.0 #TODO
nperms     = 128
nsamples   = 1
hdim       = 256
nhidden    = 2
maxcorr    = 0.005
noisebounds= [-10.0, -4.0]
[mmd.kernel]
nbandwidth = 1 #TODO
bwbounds   = [-10.0, 2.0] # bounds for kernel bandwidths (logsigma)
losstype   = "tstatistic" #"MMD"
lambda     = 0.0
stepsize   = 1e-2
epochs     = 1
nbatches   = 10
rate       = 10 #TODO

[vae]
epochs     = 999_999
batchsize  = 1_000
nbatches   = 10
traintime  = 36000.0
saveperiod = 300.0
mutations  = 0
stepsize   = 1e-4
stepdrop   = 1.0
steprate   = 1000
zdim       = 8
hdim       = 128
nhidden    = 0
gamma      = 0.5

[prior]
nterms    = 2
batchsize = 100
nbatches  = 10
logsigma  = -6.0
[prior.data]
thetas    = "/project/st-arausch-1/jcd1994/MMD-Learning/data/mlefit-v1/mlefits-shuffled.bson"
image     = "/project/st-arausch-1/jcd1994/MMD-Learning/data/images/masked-image-240x240x48x48.mat"
t2dist    = "/project/st-arausch-1/jcd1994/MMD-Learning/data/images/masked-image-240x240x48x48.t2dist.mat"
t2maps    = "/project/st-arausch-1/jcd1994/MMD-Learning/data/images/masked-image-240x240x48x48.t2maps.mat"
t2parts   = "/project/st-arausch-1/jcd1994/MMD-Learning/data/images/masked-image-240x240x48x48.t2parts.mat"
settings  = "/project/st-arausch-1/jcd1994/MMD-Learning/data/images/masked-image-240x240x48x48.settings-240x240x48x48.txt"
[prior.fitting]
losstype   = "mle"
batchsize  = 1000 # 1000 gives 822 jobs
batchindex = 1
maxtime    = 15.0
