[data]
out       = "./output/tmp"
ntheta    = 5
nsignal   = 128
theta_labels = ["freq", "phase", "offset", "amp", "tconst"]
# nsignal   = 48
# theta_labels = ["refcon", "alpha", "T2short", "dT2", "Ashort"]

[mmd]
stepsize   = 1.0e-4 #TODO
stepdrop   = 1.0 #10.0 3.1623 #1.7783
stepthresh = 0.9e-7
steprate   = 1000
batchsize  = 256 #3072 #2048 #TODO
nbatches   = 10
epochs     = 999_999
traintime  = 1e9 #18000.0 #TODO
saveperiod = 300.0 #TODO
showrate   = 1 #TODO
lambda     = 1.0 #TODO
nperms     = 128
nsamples   = 1
zdim       = 8
hdim       = 256
nhidden    = 2
[mmd.kernel]
nbandwidth = 4 #TODO
bwbounds   = [-5.0, 2.0]
losstype   = "tstatistic" #"MMD"
lambda     = 1.0
stepsize   = 1e-2
epochs     = 1
nbatches   = 10
rate       = 10 #TODO

[vae]
epochs     = 999_999
batchsize  = 1_000
nbatches   = 10
traintime  = 36000.0
saveperiod = 300.0
mutations  = 0
stepsize   = 1e-4
stepdrop   = 1.0
steprate   = 1000
zdim       = 8
hdim       = 128
nhidden    = 0
gamma      = 0.5

[prior]
method    = "simultaneous_perturbation_stochastic_approximation"
maxtime   = 1.0
nterms    = 2
batchsize = 100
nbatches  = 10
logsigma  = -6.0
