function [ ignored_folders ] = ignoredfolders( varargin )
%IGNOREDFOLDERS Folders to remove from path (contain old, testing, or
%out-dated code).

ignored_folders = { ...
    'old', 'Old', ...
    'test', 'Test', 'testing', 'Testing', ...
    'tmp', 'Temp', 'Tmp', ...
    'backup', 'Backup', ...
    'archive', 'Archive' ...
    };

if nargin > 0
    ignored_folders = [ ignored_folders, varargin{:} ];
end

end

